use std::{
    collections::HashMap,
    fs::{self, File, OpenOptions},
    io::{Read, Write},
    path::Path,
    process,
};

use colorized::{Colors, colorize_print, colorize_println};
use serde::{Deserialize, Serialize};

use crate::{
    core::hyprctl::Hyprctl,
    utils::{
        directory::get_home_dir, prompt::Prompt, terminal_command::TerminalCommand,
        value::GetOrDefault,
    },
};

use super::{app::AppResult, monitor::Monitor};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    pub monitors: HashMap<String, Monitor>,
    pub main_monitor: String,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            monitors: HashMap::new(),
            main_monitor: String::new(),
        }
    }
}

impl Config {
    pub fn new(monitors: HashMap<String, Monitor>, main_monitor_key: String) -> Self {
        Self {
            monitors,
            main_monitor: main_monitor_key,
        }
    }

    pub fn load_from_file(&mut self) -> AppResult<()> {
        let path = self.get_file_path()?;
        let mut data = String::new();
        let mut file = File::open(Path::new(&path))?;
        file.read_to_string(&mut data)?;

        let config: Config = serde_json::from_str::<Config>(&data)?;

        self.monitors = config.monitors;
        self.main_monitor = config.main_monitor;

        Ok(())
    }

    pub fn prompt_user(&mut self) -> AppResult<()> {
        TerminalCommand::clear()?;

        colorize_println("Warning: No config file found\n", Colors::YellowFg);

        let prompt = Prompt::new("Would you like to create a new config?");

        if !prompt.yes_or_no()? {
            TerminalCommand::clear()?;
            process::exit(0);
        }

        let monitor_values = Hyprctl::monitors()?;
        let mut monitor_vec: Vec<Monitor> = vec![];

        for (i, value) in monitor_values.iter().enumerate() {
            let id = value.get_number_or_default("id");
            let name = value.get_string_or_default("name");
            let description = value.get_string_or_default("description");
            let mut min_workspace_id: u64 = 1;

            if i > 0 {
                if let Some(prev_monitor) = monitor_vec.get(i - 1) {
                    min_workspace_id = prev_monitor.max_workspace_id + 1;
                }
            }

            let monitor = Monitor::new(
                id,
                name,
                description,
                min_workspace_id,
                min_workspace_id + 4,
            );

            monitor_vec.push(monitor);
        }

        TerminalCommand::clear()?;

        colorize_println(
            format!("We have detected {} monitors:", monitor_vec.len()),
            Colors::BlueFg,
        );

        for monitor in &monitor_vec {
            colorize_print("\nname: ", Colors::GreenFg);
            colorize_println(format!("{}", monitor.name), Colors::Reset);
            colorize_print("description: ", Colors::GreenFg);
            colorize_println(format!("{}\n", monitor.description), Colors::Reset);
        }

        colorize_println(
            "Set a key for each monitor (This key will be used to identify your monitor while using this tool)",
            Colors::BlueFg,
        );

        let mut monitors: HashMap<String, Monitor> = HashMap::new();

        for monitor in monitor_vec {
            let prompt = Prompt::new(format!("\nChoose a key for '{}'", monitor.name));
            let key = prompt.string()?;

            if self.main_monitor == "" {
                let prompt = Prompt::new("\nIs this your main monitor?");

                if prompt.yes_or_no()? {
                    self.main_monitor = key.clone();
                }
            }

            monitors.insert(key, monitor);
        }

        self.monitors = monitors;
        self.write_to_file()?;
        self.add_workspaces_to_hypr_config()?;

        colorize_println("\nConfig successfully created!\n", Colors::GreenFg);

        let prompt =
            Prompt::new("Configuration changes require a restart to take effect. Restart now?");
        let restart = prompt.yes_or_no()?;

        if restart {
            TerminalCommand::new("shutdown -r now").run()?;
        }

        Ok(())
    }

    pub fn write_to_file(&self) -> AppResult<()> {
        let data = serde_json::to_string_pretty(self)?;
        let file_path = self.get_file_path()?;

        if let Some(parent) = Path::new(&file_path).parent() {
            fs::create_dir_all(parent)?;
        }

        let mut file = File::create(file_path.clone())?;
        file.write_all(data.as_bytes())?;

        Ok(())
    }

    pub fn add_workspaces_to_hypr_config(&self) -> AppResult<()> {
        let mut config_string = String::new();

        config_string += "# === Generated By Hyprland Workspace Manager ===\n\n";
        config_string += "# Workspaces\n\n";

        for (key, monitor) in &self.monitors {
            let line = format!("# {}\n", key);

            config_string += line.as_str();

            for i in monitor.min_workspace_id..=monitor.max_workspace_id {
                let line = format!("workspace = {}, monitor:{}\n", i, monitor.name);

                config_string += line.as_str()
            }

            config_string += "\n";
        }

        config_string += &format!(
            "exec-once = $HOME/.local/bin/hyprland-workspace-manager focus monitor {}\n",
            self.main_monitor
        );

        let hypr_config_path = self.get_hypr_config_path()?;
        let workspaces_file_path = format!("{}/workspaces.conf", hypr_config_path);
        let hyprland_file_path = format!("{}/hyprland.conf", hypr_config_path);

        let mut file = File::create(workspaces_file_path)?;
        file.write_all(config_string.as_bytes())?;

        let command = format!("cat {}/hyprland.conf", hypr_config_path);
        let result = TerminalCommand::new(command).run_with_output()?;
        let already_cofigured = result.contains("source = ~/.config/hypr/workspaces.conf");

        if !already_cofigured {
            let mut config_string = String::new();

            config_string += "\n# === Generated By Hyprland Workspace Manager ===\n\n";
            config_string += "source = ~/.config/hypr/workspaces.conf\n\n";
            config_string += "# =====================================================\n";

            let mut file = OpenOptions::new().append(true).open(hyprland_file_path)?;
            file.write_all(config_string.as_bytes())?;
        }

        Ok(())
    }

    fn get_hypr_config_path(&self) -> AppResult<String> {
        let home_dir = get_home_dir()?;

        Ok(format!("{}/.config/hypr", home_dir))
    }

    fn get_file_path(&self) -> AppResult<String> {
        let home_dir = get_home_dir()?;

        Ok(format!(
            "{}/.config/hyprland-workspace-manager/config.json",
            home_dir
        ))
    }
}
